xychart-beta horizontal
    %% file: fruit-estimation.mmd
    title "Относителен размер на работата"
    x-axis ["Ябълка", "Авокадо", "Диня", "Цяла тиква", "Обелена тиква"]
    y-axis "Story points" 0 --> 8
    bar [1, 2, 5, 8, 3]
