import { defineRouteMiddleware, type StarlightRouteData } from '@astrojs/starlight/route-data';
import { byId, childrenOf, coursesFor, isLab, translationFor, urlFor } from './utils/courses';

type Item = StarlightRouteData['sidebar'][number];
type Link = Extract<Item, { type: 'link' }>;

export const onRequest = defineRouteMiddleware((context) => {
  const route = context.locals.starlightRoute;
  const locale = route.locale || 'bg';
  const bg = locale === 'bg';
  const courseId = route.id.split('/').slice(0, 2).join('/');
  const course = byId.get(courseId);
  const overview = bg ? 'Преглед' : 'Overview';
  route.head = route.head.flatMap((entry) => {
    if (entry.tag !== 'link') return [entry];
    if (entry.attrs?.rel === 'alternate') {
      const language = entry.attrs.hreflang;
      const target = language === 'bg' || language === 'en'
        ? (route.id === locale ? byId.get(language) : translationFor(route.id, language)) : undefined;
      return target ? [{ ...entry, attrs: { ...entry.attrs, href: `https://programmingfundamental.github.io${urlFor(target.id)}` } }] : [];
    }
    if (route.id === '404' && entry.attrs?.rel === 'canonical') return [{ ...entry, attrs: { ...entry.attrs, href: 'https://programmingfundamental.github.io/courses/404.html' } }];
    return [entry];
  });
  const link = (id: string, label?: string): Link => ({
    type: 'link', href: urlFor(id), label: label || byId.get(id)?.data.sidebar.label || byId.get(id)?.data.title || id,
    isCurrent: route.id === id, badge: undefined, attrs: {},
  });
  const group = (label: string, entries: Item[], collapsed = true): Item => ({ type: 'group', label, entries, collapsed, badge: undefined });

  // Relabel native autogenerated groups from their index page and keep only
  // actual translations. Starlight still renders the sidebar and mobile menu.
  function clean(items: Item[], prefix: string): Item[] {
    return items.flatMap((item): Item[] => {
      if (item.type === 'link') {
        const id = decodeURI(item.href).replace(/^\/courses\//, '').replace(/\/$/, '');
        return byId.has(id) ? [{ ...item, label: id === prefix ? overview : item.label }] : [];
      }
      const id = `${prefix}/${item.label}`;
      const entries = clean(item.entries, id);
      if (!entries.length) return [];
      const index = byId.get(id);
      const label = index?.data.sidebar.label || index?.data.title || item.label.replaceAll('-', ' ');
      entries.sort((a,b) => {
        const weight = (entry: Item): number => {
          if (entry.type === 'link') return entry.href === urlFor(id) ? -1 : (byId.get(decodeURI(entry.href).replace(/^\/courses\//,'').replace(/\/$/,''))?.data.sidebar.order ?? 999);
          const child = childrenOf(id).find((doc) => doc.data.title === entry.label || doc.data.sidebar.label === entry.label);
          return child?.data.sidebar.order ?? 999;
        };
        return weight(a) - weight(b);
      });
      return [group(label, entries, !route.id.startsWith(id + '/') && route.id !== id)];
    });
  }
  const originalCourse = route.sidebar.find((item) => item.type === 'group' && item.label === courseId.split('/')[1]);
  const allCourses = coursesFor(locale).map((doc) => link(doc.id));
  if (course && originalCourse?.type === 'group') {
    const entries = clean(originalCourse.entries, courseId);
    const labEntries: Item[] = [];
    const otherEntries: Item[] = [];
    for (const entry of entries) {
      const href = entry.type === 'link' ? entry.href : entry.entries.find((child) => child.type === 'link')?.href;
      if (href === urlFor(courseId)) continue;
      const part = href?.replace(urlFor(courseId), '').split('/')[0] || '';
      (isLab(part) ? labEntries : otherEntries).push(entry);
    }
    // Index frontmatter determines group order; filenames are only a tie-breaker.
    const labs = childrenOf(courseId).filter((doc) => isLab(doc.id.split('/').at(-1)!));
    const labRank = (item: Item) => labs.findIndex((doc) => item.type === 'link' ? item.href === urlFor(doc.id) : item.label === (doc.data.sidebar.label || doc.data.title));
    labEntries.sort((a,b) => labRank(a) - labRank(b));
    route.sidebar = [
      link(locale, bg ? 'Всички курсове' : 'All courses'),
      group(course.data.title, [link(courseId, overview)], false),
      ...(labEntries.length ? [group(bg ? 'Лабораторни упражнения' : 'Labs', labEntries, false)] : []),
      ...(otherEntries.length ? [group(bg ? 'Допълнителни материали' : 'Additional resources', otherEntries)] : []),
      group(bg ? 'Други курсове' : 'Other courses', allCourses),
    ];
    const currentLab = labs.findIndex((doc) => doc.id === route.id);
    if (currentLab >= 0) {
      route.pagination = {
        prev: currentLab > 0 ? link(labs[currentLab - 1]!.id) : link(courseId, overview),
        next: labs[currentLab + 1] ? link(labs[currentLab + 1]!.id) : undefined,
      };
    } else {
      const flatten = (items: Item[]): Link[] => items.flatMap((item) => item.type === 'link' ? [item] : flatten(item.entries));
      const sequence = flatten([link(courseId, overview), ...labEntries, ...otherEntries]);
      const position = sequence.findIndex((item) => item.isCurrent);
      route.pagination = { prev: sequence[position - 1], next: position >= 0 ? sequence[position + 1] : undefined };
    }
  } else {
    route.sidebar = [group(bg ? 'Курсове' : 'Courses', allCourses, false)];
    route.pagination = {prev: undefined, next: undefined};
  }
});
